### PR TITLE
Added SparkClustering notebook

### PR DESCRIPTION
**Pull request by yuchaoran2011**
Due to inconsistent performances in BatchKMeans, only SparkClustering notebook is included in alpha3 release.

### CODE REVIEW

**Comment by debasishg** [comment]
LGTM

**Comment by loverdos** [comment]
I thought we said during the meeting to re-issue the PR against the release branch ...

**Comment by yuchaoran2011** [comment]
That's what I did, no? The same set of changes made against master and the release branches.

**Comment by debasishg** [comment]
Chaoran - I thought you will open another PR against the release branch - no ?

**Comment by yuchaoran2011** [comment]
@debasishg #7 is the same changes made against the release branch.

**Comment by loverdos** [comment]
This is merged to master now, not the release branch. So work for the release continues on the release branch and when we say it is all done, we merge the whole of the release branch back to master and tag the release.

**Comment by loverdos** [comment]
Anyway, let's leave it as it is for now, I'll have to document the process a bit for the next release.

**Comment by yuchaoran2011** [comment]
Got it. We should do that. Make PRs against the release branch and then backport to master when done.

**Pull request merged**
