### PR TITLE
Upgrade to 0.7.1

### PR DESCRIPTION
**Pull request by yuchaoran2011**
0.7.1 release notes: http://zeppelin.apache.org/releases/zeppelin-release-0.7.1.html. Fixes include "Propagate interpreter exception to frontend" and "Zombie Interpreter processes" will help with debug.

### CODE REVIEW

**Comment by yuchaoran2011** [comment]
Pushing through. The latest image is now pushed to lightbend/zeppelin:0.7.1

**Comment by loverdos** [comment]
How is the image pushed to lightbend/? Do we have a build script?

**Comment by yuchaoran2011** [comment]
It's pushed manually for now. I'll add a build script.

**Comment by loverdos** [comment]
Beware this is a public repository (I am referring to credentials and any sensitive information).

**Pull request merged**
